metr = int(input("Введите количество метров: "))
print(f"В {metr} метрах {metr * 100} сантиметров")
print(f"В {metr} метрах {metr * 10} дециметров")
print(f"В {metr} метрах {metr * 1000} миллиметров")
print(f"В {metr} метрах {metr / 1600} миль")